//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTIGraduationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraInvitation
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string NationalId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> PresenceDateTime { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
