//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTIGraduationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> Chair1Id { get; set; }
        public Nullable<int> Chair2Id { get; set; }
    }
}
